/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MetroTicket;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author GameWorks
 */
public class MT_01_SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form MT_01_SplashScreen
     */
    public MT_01_SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MT_01_Discount_jtx = new javax.swing.JTextField();
        MT_01_Destination_jtx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MT_01_Departure_jtx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MT_01_Class_jtx = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MT_01_Price_jtx = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MT_01_Quantity_jtx = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MT_01_Total_jtx = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MT_01_Exit_jbtn = new javax.swing.JButton();
        MT_01_Add_jbtn = new javax.swing.JButton();
        MT_01_Update_jbtn = new javax.swing.JButton();
        MT_01_Print_jbtn = new javax.swing.JButton();
        MT_01_Reset_jbtn = new javax.swing.JButton();
        MT_01_Delete_jbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MetroTicket");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 400, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Discount");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 400, 60));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sample Places");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 80));

        MT_01_Discount_jtx.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jPanel2.add(MT_01_Discount_jtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 480, 60));

        MT_01_Destination_jtx.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        MT_01_Destination_jtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MT_01_Destination_jtxActionPerformed(evt);
            }
        });
        jPanel2.add(MT_01_Destination_jtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 480, 60));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Destination");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 400, 60));

        MT_01_Departure_jtx.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        MT_01_Departure_jtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MT_01_Departure_jtxActionPerformed(evt);
            }
        });
        jPanel2.add(MT_01_Departure_jtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 480, 60));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Departure");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 400, 60));

        MT_01_Class_jtx.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jPanel2.add(MT_01_Class_jtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 480, 60));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Class");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 400, 60));

        MT_01_Price_jtx.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jPanel2.add(MT_01_Price_jtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 480, 60));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Price");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 400, 60));

        MT_01_Quantity_jtx.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        MT_01_Quantity_jtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MT_01_Quantity_jtxActionPerformed(evt);
            }
        });
        jPanel2.add(MT_01_Quantity_jtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 480, 60));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Quantity");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 400, 60));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 400, 60));

        MT_01_Total_jtx.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jPanel2.add(MT_01_Total_jtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 480, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Departure", "Destination", "Class", "Quantity", "Price", "Discount", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 870, 300));

        MT_01_Exit_jbtn.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        MT_01_Exit_jbtn.setText("Exit");
        MT_01_Exit_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MT_01_Exit_jbtnActionPerformed(evt);
            }
        });
        jPanel2.add(MT_01_Exit_jbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 520, 410, 70));

        MT_01_Add_jbtn.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        MT_01_Add_jbtn.setText("Add");
        MT_01_Add_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MT_01_Add_jbtnActionPerformed(evt);
            }
        });
        jPanel2.add(MT_01_Add_jbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 410, 70));

        MT_01_Update_jbtn.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        MT_01_Update_jbtn.setText("Update");
        jPanel2.add(MT_01_Update_jbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 410, 70));

        MT_01_Print_jbtn.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        MT_01_Print_jbtn.setText("Print");
        MT_01_Print_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MT_01_Print_jbtnActionPerformed(evt);
            }
        });
        jPanel2.add(MT_01_Print_jbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 410, 70));

        MT_01_Reset_jbtn.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        MT_01_Reset_jbtn.setText("Reset");
        jPanel2.add(MT_01_Reset_jbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, 410, 70));

        MT_01_Delete_jbtn.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        MT_01_Delete_jbtn.setText("Delete");
        jPanel2.add(MT_01_Delete_jbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, 410, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1920, 960));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MT_01_Add_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MT_01_Add_jbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MT_01_Add_jbtnActionPerformed

    private void MT_01_Print_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MT_01_Print_jbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MT_01_Print_jbtnActionPerformed

    private void MT_01_Departure_jtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MT_01_Departure_jtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MT_01_Departure_jtxActionPerformed

    private void MT_01_Destination_jtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MT_01_Destination_jtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MT_01_Destination_jtxActionPerformed

    private void MT_01_Quantity_jtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MT_01_Quantity_jtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MT_01_Quantity_jtxActionPerformed
private JFrame frame;
    private void MT_01_Exit_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MT_01_Exit_jbtnActionPerformed
        
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Do you want to eit?", "MetroTicket", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_MT_01_Exit_jbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MT_01_SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MT_01_SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MT_01_SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MT_01_SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MT_01_SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MT_01_Add_jbtn;
    private javax.swing.JTextField MT_01_Class_jtx;
    private javax.swing.JButton MT_01_Delete_jbtn;
    private javax.swing.JTextField MT_01_Departure_jtx;
    private javax.swing.JTextField MT_01_Destination_jtx;
    private javax.swing.JTextField MT_01_Discount_jtx;
    private javax.swing.JButton MT_01_Exit_jbtn;
    private javax.swing.JTextField MT_01_Price_jtx;
    private javax.swing.JButton MT_01_Print_jbtn;
    private javax.swing.JTextField MT_01_Quantity_jtx;
    private javax.swing.JButton MT_01_Reset_jbtn;
    private javax.swing.JTextField MT_01_Total_jtx;
    private javax.swing.JButton MT_01_Update_jbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
